---
name: "Kitsu (nep fork)"
guid: "71d15fb1-c980-43f1-8646-3ba15c3ee68e"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kitsu.png"
version: 7
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider

category: "Anime"
owner: "nepellion"
artifacts:
  - "Jellyfin.Plugin.Kitsu.dll"
changelog: |-
  - Jellyfin 10.11 support (#37) @crobibero
